version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - .data/static:/opt/app/static
      - .data/media:/opt/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.25.3
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf
      - .data/static:/opt/app/static
      - .data/media:/opt/app/media
    depends_on:
      - backend
    ports:
      - "8080:80"


  db:
    container_name: database
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
